app:
  name: "BootExample"
  version: "1.0.0"
  env: "development"
  
logger:
  enabled: true
  level: "debug"
  json: false
  
web:
  enabled: true
  port: 8080
  host: "0.0.0.0"
  
cache:
  enabled: true
  type: "memory"
  
database:
  enabled: false
  
custom:
  enabled: true 