# 管理面板配置
admin:
  host: "127.0.0.1"
  port: 8081
  base_path: "/admin"
  swagger:
    enabled: true
  security:
    secret_key: "admin-secret-key"

# 日志配置
logger:
  level: "debug"
  console_output: true
  file_output: true
  filename: "logs/admin.log"
  max_size: 10
  max_backups: 5
  max_age: 30
  compress: true 